### ISSUE TITLE
IllegalArgumentException: Entity may not be null

### ISSUE THREAD

**Issue by netmackan** [netmackan/java-binrepo-proxy#5]
```
Incoming connection from /127.0.0.1
Outgoing connection to repo1.maven.org/185.31.17.209
New connection thread
>> Request URI: /maven2/junit/junit/4.11/junit-4.11.pom
Is acceptable?: /maven2/junit/junit/4.11/junit-4.11.pom
Will fetch GET /maven2/junit/junit/4.11/junit-4.11.pom.asc HTTP/1.1
Read body of 535 bytes
-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2.0.18 (Darwin)
Comment: GPGTools - http://gpgtools.org

iQEcBAABAgAGBQJQo+9kAAoJEMfLMlRniTzEnCUH/33xH+STEh+OLdrK2bAEJYS1
nIL1UeV76RxveXXWAbAFSE1OVs/2xqKfRVCimSvGv7wBAbLzOQMC5C/X8iUsvt/L
x35aJbVDR92uh71oWKz7t+0SWvJnvkFhHq/seqzF8FwJtptqLZAkSCkZsM5s9GjI
//Kl07olAfcAU/TQY+EMx0Ov+4BlEEkjnof0k1dceltSBQvdQoZsBC5cCnH8G6Yn
VkUntnrvsUBhrmBEo1DDQr5aBWMP1si4gqmvY9W6Flj8P9Gb+4XRXpwnVRWOYu3B
8IhjCWHwUhxY0XwRhF8hUqDPxDpWCIojrP+JSS0WJvHKjhDkGCVMSCBEF0G7JTU=
=Vecm
-----END PGP SIGNATURE-----

Exception in thread "Thread-143" java.lang.IllegalArgumentException: Entity may not be null
        at org.apache.http.util.Args.notNull(Args.java:54)
        at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:121)
        at com.markuspage.jbinrepoproxy.standalone.transport.httpcore.HttpCoreTransportClientImpl.httpGetTheFile(HttpCoreTransportClientImpl.java:86)
        at com.markuspage.jbinrepoproxy.standalone.Main$1.handleRequest(Main.java:128)
        at com.markuspage.jbinrepoproxy.standalone.transport.httpcore.HttpCoreTransportServer$ProxyHandler.handle(HttpCoreTransportServer.java:237)
        at org.apache.http.protocol.HttpService.doService(HttpService.java:436)
        at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:341)
        at org.apache.http.examples.ElementalReverseProxy$ProxyThread.run(ElementalReverseProxy.java:289)
```

Still seems to work though.

**Comment by netmackan** [comment]
This only affects the HttpCore implementation.
